name: Run Python Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found. Skipping dependency installation."
        fi

    # Step 4: Run all Python scripts
    - name: Run Python scripts
      run: |
        for file in $(find . -name "*.py"); do
          echo "Running $file"
          python "$file"
        done
